# Generated by Django 4.0.6 on 2022-08-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('role', models.IntegerField(choices=[('ADMIN', 'Admin'), ('BUSINESS_OWNER', 'Business Owner'), ('END_USER', 'EndUser'), ('STAFF_USER', 'StaffUser')], default=3)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=20, null=True)),
                ('verification_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('forgot_pass_token', models.CharField(blank=True, max_length=20, null=True)),
                ('forgot_pass_token_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
