# Generated by Django 4.0.6 on 2022-08-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_type']},
        ),
    ]
