# Generated by Django 4.0.6 on 2022-08-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
