# Generated by Django 4.0.6 on 2022-08-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_address_coupon_order_refund_payment_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='model',
            new_name='item',
        ),
    ]
