# Generated by Django 4.0.6 on 2022-08-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='product_name',
        ),
    ]
