# Generated by Django 4.0.6 on 2022-08-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Billing_Address', 'Billing'), ('Shipping_Address', 'Shipping')], max_length=30),
        ),
    ]
