# Generated by Django 4.0.6 on 2022-08-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_shippingaddress_is_billing_address_same'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='amount',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(choices=[('15%off-ICIC_CC ', '15% off upto rs.1500 on ICICI Credit Card'), ('10% off-HDFC_CC ', '10% off on upto rs.3000 on HDFC Credit Card'), ('15% CB-HDFC-DB ', '15% Cashback upto rs.1500 on HDFC Debit Card'), ('10% CB-ICICI-DB ', '15% Cashback upto rs.3000 on ICICI Debit Card')], max_length=50),
        ),
    ]
