# Generated by Django 4.0.6 on 2022-08-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='code1',
        ),
    ]
