# Generated by Django 4.0.6 on 2022-08-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_rename_code_coupon_code1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code1',
            new_name='code',
        ),
    ]
