# Generated by Django 4.0.6 on 2022-08-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_rename_code1_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
