# Generated by Django 4.0.6 on 2022-08-24 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_alter_checkout_ordered_date_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 5, 20, 9, 198157, tzinfo=utc)),
        ),
    ]
