# Generated by Django 4.0.6 on 2022-08-24 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_alter_checkout_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 10, 34, 42, 992699, tzinfo=utc)),
        ),
    ]
