# Generated by Django 4.0.6 on 2022-08-26 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_alter_checkout_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='userid',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 4, 54, 28, 642265, tzinfo=utc)),
        ),
    ]
