# Generated by Django 4.0.6 on 2022-08-26 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_checkout_userid_alter_checkout_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 5, 47, 31, 224161, tzinfo=utc)),
        ),
    ]
